### ISSUE TITLE
SSL_VERIFY_NONE for r2d2 pool ?

### ISSUE THREAD

**Issue by nicolasbauw** [matthewkmayer/matthewkmayer.github.io#87]
Hi,

First, thanks for the postgres-tls-tester, it's the only working code I found for use in Rocket / Postgres / SSL.

I have trouble to disable the certificate verification in the last part of the code (when the connection pool is created), the code works on my dev machine with a self signed certificate, but I need to disable that certificate check for use with my DB provider (I only need the data to be encrypted).

I can disable that check when not using the r2d2 pool in some test programs, but I don't find anything to do this with the r2d2 pool, maybe you can help me ? :-)

Nicolas

**Comment by nicolasbauw** [comment]
I found the solution ! I just used the same method as the ping:

`
let mut connbuilder = SslConnectorBuilder::new(SslMethod::tls()).unwrap();
    match dbssl.to_lowercase().as_ref() {
        "require" | "prefer" | "allow" => connbuilder.set_verify(postgres::tls::openssl::openssl::ssl::SSL_VERIFY_NONE),
        _ => (), // by default we verify certs: it's like either verify-ca or verify-full, TBD
    }
    
    let negotiator = Box::new(::postgres::tls::openssl::OpenSsl::from(connbuilder.build()));
    let db_ssl_mode = match dbssl.to_lowercase().as_ref() {
        "require" | "verify-ca" | "verify-full" => TlsMode::Require(negotiator),
        // `prefer` and `allow` fall into here and will not try TLS. 
        // Not totally correct: please use at least `require` for real use.
        _ => TlsMode::None, 
    };
`

I tried that before without success, in fact the mess was just with the modules import.

**Comment by matthewkmayer** [comment]
Excellent!

Getting the imports correct was the hardest part of the sample. Glad to hear it helped and you figured out the connection pooling. 😄
